In [12]:
#3.Import the numpy package under the name np
import numpy as np

#4.Create a 3x3 matrix with values ranging from 0 t0 8
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#5.What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [14]:
#6.Is the following expressions true?
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Pavilion\Anaconda2\lib\site-packages\ipykernel\__main__.py:2: RuntimeWarning: invalid value encountered in sqrt
  from ipykernel import kernelapp as app


False

In [15]:
#7.Create a random vector of size 30 and find the mean value
S = np.random.random(30)
x = S.mean()
print(x)

0.431373893764


In [16]:
#8.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
P = np.dot(np.ones((5,3)), np.ones((3,2)))
print(P)


[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [17]:
#9.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
W = np.dot(np.ones((5,3)), np.ones((3,2)))
print(W)

[[ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]
 [ 3.  3.]]


In [19]:
#10.Create a random vector of size 10 and sort it
W = np.random.random(10)
np.sort(W)

array([ 0.26032553,  0.26121797,  0.33518929,  0.36252866,  0.43896338,
        0.50932665,  0.55744924,  0.8034033 ,  0.85895845,  0.87271837])

In [24]:
#11.Create a random vector vector of size 100 and replace the maximum value by 0
import numpy as np
W = np.random.random(10)
W[W.argmax()]=0
print(W)

[ 0.17439531  0.37975033  0.44667444  0.          0.77456564  0.63779351
  0.26311115  0.92339187  0.8902166   0.14193007]


In [34]:
#12.How to get the diagonal of a dot product?
import numpy as np
a = np.arange(15).reshape(5, 3)
b = np.arange(9).reshape(3, 3)
np.einsum('ij,jk,ki->i', a, b, a.T)




array([  60,  672, 1932, 3840, 6396])